### ISSUE TITLE
HTMLTestRunner

### ISSUE THREAD

**Issue by nunterr** [SeldomQA/XTestRunner#1]
你更改后的版本，我在python2.7.13版本可以使用，python3.6.1版本会报错

EF.1.2Traceback (most recent call last):
  File "HTMLTestRunner.py", line 826, in <module>
    main(module=None)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 94, in __init__
    self.runTests()
  File "HTMLTestRunner.py", line 817, in runTests
    unittest.TestProgram.runTests(self)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/main.py", line 255, in runTests
    self.result = testRunner.run(self.test)
  File "HTMLTestRunner.py", line 632, in run
    self.generateReport(test, result)
  File "HTMLTestRunner.py", line 689, in generateReport
    self.stream.write(output.encode('utf8'))
TypeError: write() argument must be str, not bytes

**Comment by piotrkochan** [comment]
same here
