### ISSUE TITLE
求助：发送邮件功能报错提示“smtplib.SMTPResponseException: (454, b'Command not permitted when TLS active')”

### ISSUE THREAD

**Issue by xuanchangxian** [SeldomQA/XTestRunner#41]
求助：发送邮件功能报错提示“smtplib.SMTPResponseException: (454, b'Command not permitted when TLS active')”
代码：
import unittest
from XTestRunner import HTMLTestRunner
from XTestRunner import SMTP

if __name__ == '__main__':
    report = "./reports/all_result.html"
    smtp = SMTP(user="18668922098@163.com", password="CXAYTNLONNILAXIZ", host="smtp.163.com", ssl=True)
    smtp.sender(to=["18668922098@163.com", "824353900@qq.com"], subject="智慧大脑UI自动化测试报告", attachments=report)

报错：
Traceback (most recent call last):
  File "D:\WorkCode\ZhdnUiCodes\test_case\lib.py", line 9, in <module>
    smtp.sender(to=["18668922098@163.com", "824353900@qq.com"], subject="智慧大脑UI自动化测试报告", attachments=report)
  File "C:\Program Files\Python311\Lib\site-packages\XTestRunner\_email.py", line 91, in sender
    smtp.starttls()
  File "C:\Program Files\Python311\Lib\smtplib.py", line 805, in starttls
    raise SMTPResponseException(resp, reply)
smtplib.SMTPResponseException: (454, b'Command not permitted when TLS active')

**Comment by xuanchangxian** [comment]
邮箱已配置SMTP服务
