### ISSUE TITLE
发送邮件失败

### ISSUE THREAD

**Issue by netassa** [SeldomQA/XTestRunner#44]
![1712660913288(1)](https://github.com/SeldomQA/XTestRunner/assets/17811689/ad52c8d5-8847-44d6-ac96-3593e7123ef7)
像上面这样写，发送邮件失败，报如下错误：
Traceback (most recent call last):
  File "f:\work\python\POProject\test\case\test3.py", line 47, in <module>
    runner.send_email(
  File "D:\software\python\lib\site-packages\XTestRunner\htmlrunner\runner.py", line 505, in send_email
    smtp.sender(to=to, subject=subject, attachments=attachments)
  File "D:\software\python\lib\site-packages\XTestRunner\_email.py", line 91, in sender
    smtp.starttls()
  File "D:\software\python\lib\smtplib.py", line 805, in starttls
    raise SMTPResponseException(resp, reply)
smtplib.SMTPResponseException: (454, b'Command not permitted when TLS active')

**Comment by netassa** [comment]
commit[3eb654b](https://github.com/SeldomQA/XTestRunner/commit/3eb654b5e202fc3af9a8ad2fea5909dd0ef3437d)已修复.
